# -*- coding: utf-8 -*-
"""Data Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdTuwbfFtaUxpNbDqFfvzdAZ62iEkw54
"""

#!pip install langchain langchain_community langchain_core pymupdf langchain_google_genai

from langchain.document_loaders import PyMuPDFLoader
from langchain_core.pydantic_v1 import BaseModel , Field

loader = PyMuPDFLoader('test.pdf')

documents = loader.load()

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0, api_key='AIzaSyBS6jDh5a4osRtHXNRDqWtax3h3DZBBT5g')

splitter = RecursiveCharacterTextSplitter(
    chunk_size = 1000,
    chunk_overlap = 150
)

def data_extraction(start_pg, ending_pg , data_pydantic_class, prompt):
    selected_docs = [
    doc for doc in documents
    if (start_pg - 1) <= doc.metadata.get('page', -1) <= (ending_pg -1)
    ]
    text = splitter.split_documents(selected_docs)
    llm_str = llm.with_structured_output(data_pydantic_class , method = 'json_schema')
    message = [
        (
            'system',
              prompt
        ),
        (
            'user',
            f'Content: {text}'
        )
    ]

    response = llm_str.invoke(message)

    return response



from typing import Literal
CauseTypeLiteral = Literal[
    "Ground movement",
    "Transportation machinery (winding)",
    "Transportation machinery (non winding)",
    "Machinery other than transp. machinery",
    "Explosives",
    "Electricity",
    "Dust, gas & other combustible material",
    "Falls (other than fall of ground)",
    "Other causes"
]

CauseCodeLiteral = Literal[
    "0111", "0112", "0113", "0114", "0115", "0116", "0117", "0118", "0119",
    "0221", "0222", "0223", "0224", "0225", "0228", "0229",
    "0331", "0332", "0333", "0334", "0335", "0336", "0339",
    "0441", "0442", "0443", "0444", "0445", "0446", "0447", "0448", "0449",
    "0551", "0552", "0553", "0554", "0555", "0556", "0557", "0558", "0559",
    "0661", "0662", "0663", "0664", "0665", "0669",
    "0771", "0772", "0774", "0775", "0776", "0777", "0778", "0779",
    "0881", "0882", "0883", "0889",
    "0991", "0992", "0993", "0994", "0995", "0999"
]

CauseDecodeLiteral = Literal[
    # Ground movement
    "Fall of roof",
    "Fall of sides (other than overhangs)",
    "Fall of overhang",
    "Rock burst/bumps",
    "Air blast",
    "Premature collapse of workings/pillars",
    "Subsidence",
    "Landslide",
    "Collapse of shaft",
    # Transportation machinery (winding)
    "Overwinding of cages/skip, etc. (upgoing)",
    "Breakage of rope, chain, draw/suspn. gear",
    "Falls of persons from cages, skip, etc.",
    "Falling of objects from cages, skip, etc.",
    "Hit by cages, skip, etc.",
    "Overwinding of cages/skip (downgoing)",
    "Other accident due to winding operation",
    # Transportation machinery (non winding)
    "Aerial ropeway",
    "Rope haulage",
    "Other rail transportation",
    "Conveyors",
    "Dumpers",
    "Wagon movements",
    "Wheeled trackless (truck, tanker, etc.)",
    # Machinery other than transp. machinery
    "Drilling machines",
    "Cutting machines",
    "Loading machines",
    "Haulage engine",
    "Winding engine",
    "Shovel, dragline, frontend loader, etc.",
    "Crushing & screening plants",
    "Other heavy earth moving machinery",
    "Other non-transportation machinery",
    # Explosives
    "Solid blasting projectiles",
    "Deep hole blasting projectiles",
    "Secondary blasting projectiles",
    "Other projectiles",
    "Misfires/sockets (while drilling into)",
    "Misfire/socket (other than drilling into)",
    "Delayed ignition",
    "Blown through shots",
    "Other explosive accident",
    # Electricity
    "Overhead lines",
    "Trailing cables",
    "Switch gears, gate end boxes, pommel, etc.",
    "Energized machines",
    "Power cables other than trailing cables",
    "Other electrical accidents",
    # Dust, gas & other combustible material
    "Occurrence of gas",
    "Influx of gas",
    "Explosion/ignition of gas/dust, etc.",
    "Outbreak of fire or spontaneous heating",
    "Well blowout (with fire)",
    "Well blowout (without fire)",
    "Other combustible material",
    "Other accidents due to dust/gas/fire",
    # Falls (other than fall of ground)
    "Fall of person from height/into depth",
    "Fall of persons on the same level",
    "Fall of objects incl. rolling objects",
    "Other accident due to falls",
    # Other causes
    "Irruption of water",
    "Flying pieces (except due to explosives)",
    "Drowning in water",
    "Buried in sands, etc.",
    "Bursting/leakage of oil pipe lines",
    "Unclassified"
]

# Extracting all of the recored mining accidents
class Victim(BaseModel):
  name: str = Field(description="Name of the victim")
  age: int = Field(description="Age of the victim")
  gender: str = Field(description="Gender of the victim")
  occupation: str = Field(description="Occupation of the victim")
  status: str = Field(description="Status of the victim , 'Dead' or 'Alive'")

class MineAccidents(BaseModel):
  date: str = Field(description="Date of the accident")
  time: str = Field(description="Time of the accident")
  mine_name: str = Field(description="Name of the mine where the accident occured")
  owner: str = Field(description="Owner of the mine")
  cause_type : CauseTypeLiteral = Field(description="Type of the cause")
  cause_code : CauseCodeLiteral = Field(description="Code of the cause")
  cause_description : CauseDecodeLiteral = Field(description="Description of the cause")
  state: str = Field(description="State of the mine")
  district: str = Field(description="District of the mine")
  mineral: str = Field(description="Mineral mined")
  victims: list[Victim] = Field(description="List of all victims")
  summary: str = Field(description="Summary of the accident")
  remarks: str = Field(description="Remarks about the accident")
class RecordedAccidents(BaseModel):
  accidents: list[MineAccidents] = Field(description="List of all recorded accidents")

prompt_recorded_accidents = """
Study each of the following accident and list down the details based on the content provided by the user.
"""

recorded_data = data_extraction(120,143 , RecordedAccidents, prompt_recorded_accidents)

recorded_data.accidents[61]

#Mine accident death+ inj data extraction


class MinesAccident(BaseModel):
  mine_name: str = Field(description="Name of the mine")
  date: str = Field(description="Date of the mine")
  killed: str = Field(description="Number of people killed")
  injured: str = Field(description="Number of people injured")
  cause_code : CauseCodeLiteral = Field(description="Code of the cause")
  cause_description : CauseDecodeLiteral = Field(description="Description of the cause")

class MinesInfo(BaseModel):
  mines : list[MinesAccident] = Field(description="List of all the mines")

prompt_mine_acc = """
You are required to study each of the following row of the mines accident and list down all the details.
"""
mine_acc_data = data_extraction(143,147 , MinesInfo, prompt_mine_acc)

mine_acc_data.mines

#Accidents + casuality report

from pydantic import BaseModel, Field
from typing import List, Optional

class AccidentStats(BaseModel):
    """
    Stores the accident and casualty counts for a specific
    location (e.g., Below Ground) or as a total.
    """
    fatal_acc: int = Field(0, description="Number of fatal accidents")
    fatal_kill: int = Field(0, description="Number of persons killed")
    fatal_inj: int = Field(0, description="Persons seriously injured *in* fatal accidents")
    serious_acc: int = Field(0, description="Number of serious accidents")
    serious_inj: int = Field(0, description="Persons seriously injured *in* serious accidents")

class AccidentByCause(BaseModel):
    """
    Represents a single row in Table 4.7, breaking down
    accidents by a specific cause and where they occurred.
    """
    cause: CauseTypeLiteral = Field(
        description="The detailed cause of the accident (e.g., 'Fall of Roof')"
    )
    below_ground: AccidentStats = Field(
        description="A dictionary of all accident stats (fatal_acc, fatal_kill, etc.) for 'Below Ground'."
    )
    open_cast: AccidentStats = Field(
        description="A dictionary of all accident stats (fatal_acc, fatal_kill, etc.) for 'Open Cast'."
    )
    above_ground: AccidentStats = Field(
        description="A dictionary of all accident stats (fatal_acc, fatal_kill, etc.) for 'Above Ground'."
    )
    # --- THIS FIELD WAS MISSING ---
    total: AccidentStats = Field(
        description="A dictionary of the total accident stats (fatal_acc, fatal_kill, etc.) across all locations."
    )

class AccidentReports(BaseModel):
    """
    The main model to hold a list of all extracted accident records.
    The final JSON must have an "accidents" key.
    """
    accidents: List[AccidentByCause] = Field(description="A list of all accident causes found in the table.")

acc_prompt = """
You are an expert data extraction assistant. Your task is to extract detailed accident statistics from the provided text, which contains Table 4.7 (pages 100-103).

You must find *all* accident cause rows in the table and format them into a list named "accidents".

For *each row* in that list, you must extract:
1.  **cause**: The name of the accident cause.
2.  **below_ground**: A dictionary of all statistics for "BELOW GROUND".
3.  **open_cast**: A dictionary of all statistics for "OPEN CAST".
4.  **above_ground**: A dictionary of all statistics for "ABOVE GROUND".
5.  **total**: A dictionary of all statistics for "TOTAL".

For each location's dictionary (below_ground, open_cast, etc.), you must find:
* `fatal_acc`: The count under "Fatal Accident -> ACC"
* `fatal_kill`: The count under "Fatal Accident -> KILL"
* `fatal_inj`: The count under "Fatal Accident -> INJ"
* `serious_acc`: The count under "S/Accident -> ACC"
* `serious_inj`: The count under "S/Accident -> INJ"

If a value is missing or is a dash, use 0. Make sure to process all rows, including the "TOTAL" rows for each cause group (e.g., "TOTAL : Fall of Roof").
"""

acc_data = data_extraction(113, 116, AccidentReports, acc_prompt)

len(acc_data.accidents)

#Table 4.6a
class CasualtyCount(BaseModel):
    """Holds the male and female casualty counts for one location."""
    male: int = Field(0, description="Male casualties")
    female: int = Field(0, description="Female casualties")

class CasualtyDetails(BaseModel):
    """
    A nested dictionary breaking down casualties by the
    place they occurred (Below, Opencast, Above, Total).
    """
    below_ground: CasualtyCount = Field(
        description="Casualties occurring Below Ground"
    )
    opencast_ground: CasualtyCount = Field(
        description="Casualties occurring in Opencast Ground"
    )
    above_ground: CasualtyCount = Field(
        description="Casualties occurring Above Ground"
    )
    total: CasualtyCount = Field(
        description="Total casualties (Male, Female)"
    )

class LocationAccidentStats(BaseModel):
    """
    Represents a single row from Table 4.6a, detailing accidents
    for a specific entity (e.g., a district, a state total).
    """
    entity_name: str = Field(
        description="The name of the mineral, state, or district for the row (e.g., 'EAST GODAVARI', 'TOTAL : ASSAM')"
    )
    fatal_accidents: int = Field(
        description="Number of fatal accidents for this entity"
    )
    serious_accidents: int = Field(
        description="Number of serious accidents for this entity"
    )
    persons_killed: CasualtyDetails = Field(
        description="A nested dictionary of all persons killed, broken down by location"
    )
    persons_seriously_injured: CasualtyDetails = Field(
        description="A nested dictionary of all persons seriously injured, broken down by location"
    )

class AccidentByLocationReport(BaseModel):
    """
    The top-level model to hold the list of all extracted records
    from Table 4.6a. The final output will have a 'locations' key.
    """
    locations: List[LocationAccidentStats] = Field(
        description="A list of all accident records, one for each entity row in the table"
    )
acc_loc_prompt = """
You are an expert data extraction assistant. Your task is to extract all accident statistics from the provided text, which is from Table 4.6a.

The final output must be a JSON object with a single key: "locations". This key must contain a list of all the rows you find.

For *each row* in the table (e.g., "EAST GODAVARI", "TOTAL : ASSAM"), create one object in the "locations" list with the following fields:

1.  `entity_name`: The name of the row (e.g., "EAST GODAVARI", "ALL INDIA : OIL").
2.  `fatal_accidents`: The number under "Number of Accidents -> Fatal".
3.  `serious_accidents`: The number under "Number of Accidents -> Serious".
4.  `persons_killed`: A nested dictionary for the "Number of Persons Killed" section.
5.  `persons_seriously_injured`: A nested dictionary for the "Number of Persons Seriously Injured" section.

For both `persons_killed` and `persons_seriously_injured`, the nested dictionary *must* have this exact structure:
* `below_ground`: A dictionary with `male` and `female` counts.
* `opencast_ground`: A dictionary with `male` and `female` counts.
* `above_ground`: A dictionary with `male` and `female` counts.
* `total`: A dictionary with `male` and `female` counts.

If a value is missing or is a dash, use 0. Process every entity row you see in the table.
"""

acc_loc_data = data_extraction(101, 108, AccidentByLocationReport, acc_loc_prompt)

acc_loc_data.locations

class MineInfo(BaseModel):
  mine_name: str = Field(description="Name of the mine")
  state: str = Field(description="State where the mine is present")
  district: str = Field(description="District where the mine is present")
  owner: str = Field(description="Owner of the mine")
  employement: int = Field(description="Number of employees in the mine")
  mineral: str = Field(description="Mineral mined by the mine")
  killed: int = Field(description="Number of people killed")
  injured: int = Field(description="Number of people injured")
  accidents: int = Field(description="Number of accidents")
  cause_code : list[CauseCodeLiteral] = Field(description="Code of the cause")
  cause: list[CauseDecodeLiteral] = Field(description="Cause of the accident")

class MineInfoReport(BaseModel):
  mines : list[MineInfo] = Field(description="List of all the mines")

mine_info_prompt="""
Extract the information about all of the mines and list them down
"""

mine_info_data = data_extraction(0,148,MineInfoReport,mine_info_prompt)

mine_info_data